// <auto-generated />
using System;
using FirstProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstProject.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20240912191525_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.7.24405.3");

            modelBuilder.Entity("FirstProject.Models.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumOfDevelopers")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ac195296-02d9-41b8-b2a6-d52e03c1790b"),
                            Name = "Desktop App",
                            NumOfDevelopers = 10
                        },
                        new
                        {
                            Id = new Guid("685f0f79-e1c0-4b33-adbf-d9bc8085fe86"),
                            Name = "Mobile App",
                            NumOfDevelopers = 4
                        });
                });

            modelBuilder.Entity("FirstProject.Models.Domain.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ed743247-3136-4cac-a5d3-f9917edb9b32"),
                            Description = "Description: Lorem ipsum",
                            ProjectId = new Guid("ac195296-02d9-41b8-b2a6-d52e03c1790b"),
                            Title = "Desktop App design"
                        },
                        new
                        {
                            Id = new Guid("dfef3b56-e96d-417e-80ab-6bce20d5a9f3"),
                            Description = "Description: Ispum lorem",
                            ProjectId = new Guid("ac195296-02d9-41b8-b2a6-d52e03c1790b"),
                            Title = "Mobile App design"
                        });
                });

            modelBuilder.Entity("FirstProject.Models.Domain.ProjectTask", b =>
                {
                    b.HasOne("FirstProject.Models.Domain.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FirstProject.Models.Domain.Project", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
